version: "3.9"

services:
  apache:
    build: .
    container_name: ProyectoSyncFive
    ports:
      - "8081:80"
      - "8082:80"
      - "8083:80"
      - "8084:80"
      - "8085:80"
    volumes:
      - ./:/var/www/html
