version: "3.9"

services:
  apache:
    image: php:8.2-apache
    container_name: ProyectoSyncFive
    ports:
      - "8081:80"
      - "8082:80"
      - "8083:80"
      - "8084:80"
      - "8085:80"
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html

    # Optional enhancements
    command: bash -c "docker-php-ext-install mysqli && apache2-foreground"
