version: "3.9"

services:
  apache:
    image: php:8.2-apache
    container_name: miguel-apache
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html
    command: >
      bash -c "
      docker-php-ext-install pdo_mysql &&
      apache2-foreground
      "
